### ISSUE TITLE
navigation issues

### ISSUE THREAD

**Issue by peterennis** [deckgo/deckdeckgo-website#12] opened 2019-08-05 16:21 UTC
There are inconsistencies in navigation resulting in a lockout bug for swiping to next
and previous page.

It appears the behavior design is:

1. Use only the -> and <- arrows will take individual steps
2. Use swipe will move from slide to slide

e.g.
![Capture655](https://user-images.githubusercontent.com/140737/62479236-d97bf100-b761-11e9-95a0-559d2b65bcce.png)

However, at code navigation I see this:
**NOTE:** two different font sizes
![2](https://user-images.githubusercontent.com/140737/62479283-f6182900-b761-11e9-9b02-02226b9a6d96.jpg)

![3](https://user-images.githubusercontent.com/140737/62479292-fc0e0a00-b761-11e9-9be6-96315c30b2da.jpg)

At some point the swipe navigation fails and I get stuck on this page.

Pull up the menu and navigate out, but then swipe no longer works.

**Comment by peterpeterparker** [comment] 2019-08-05 17:41
I can't reproduce any errors. For me it looks like that it's a side effect of the website on mobile (click to block or unblock, see screenshot).

Regarding the padding I'll change some stuffs in the future so it should be good soon but if there is a rush, I'm not against a bit of help and a PR ;)

<img width="1096" alt="Capture d’écran 2019-08-05 à 19 40 15" src="https://user-images.githubusercontent.com/16886711/62483838-f7c10b80-b7b8-11e9-92c0-eb3b91e431ac.png">

**Comment by peterpeterparker** [comment] 2019-08-05 17:42
Therefore I close this issue but let me know if I misunderstand the side effect.

Thx for reporting it 👍

**Closed by peterpeterparker** 2019-08-05 17:42 UTC

**Comment by peterennis** [comment] 2019-08-05 18:10
@peterpeterparker 

1. Use the -> and <- buttons in the code selection and the font size change is obvious.
2. The message is "Tips: click on the code to switch between horizontal and vertical scroll"
   It seems to indicate this refers to code only.
  The message only appears once and there is no visible indication what mode is active.
  I will see if I can get a repeatable test case.

**Comment by peterpeterparker** [comment] 2019-08-05 18:14
@peterennis thx for the details

1. Yes of course, moreover than scrolling, the code slide add also a zoom effect. This is optional and totally the expected behavior

2. That's a speciality of the website and agree, maybe it would be good to enhance the UX by displaying a marker which would indicate what's the current state. I don't know if that screen might remains or not in the future, therefore it's probably, time wise, a safe bet to not implement such a feature yet but if you would like to implement such a feature of course I won't be again ;)
